<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Anjian.Automation\Anjian.Automation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="MainForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="MainForm.Designer.cs">
      <DependentUpon>MainForm.cs</DependentUpon>
    </Compile>
    <Compile Update="ImageMatchTestForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="ImageMatchTestForm.Designer.cs">
      <DependentUpon>ImageMatchTestForm.cs</DependentUpon>
    </Compile>
    <Compile Update="AmountOcrTestForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="AmountOcrTestForm.Designer.cs">
      <DependentUpon>AmountOcrTestForm.cs</DependentUpon>
    </Compile>
    <Compile Update="TextOcrTestForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="TextOcrTestForm.Designer.cs">
      <DependentUpon>TextOcrTestForm.cs</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="MainForm.resx">
      <DependentUpon>MainForm.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="ImageMatchTestForm.resx">
      <DependentUpon>ImageMatchTestForm.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="AmountOcrTestForm.resx">
      <DependentUpon>AmountOcrTestForm.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="TextOcrTestForm.resx">
      <DependentUpon>TextOcrTestForm.cs</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\tessdata\eng.traineddata" Link="tessdata\eng.traineddata">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
