using System.Drawing;
using System.Windows.Forms;

namespace Anjian;

public sealed partial class PdfTableValueTestForm
{
    private TableLayoutPanel rootLayout = null!;
    private GroupBox grpOptions = null!;
    private TableLayoutPanel optionsLayout = null!;
    private Label lblPdfPath = null!;
    private TextBox txtPdfPath = null!;
    private Button btnBrowsePdf = null!;
    private Label lblRowLabel = null!;
    private TextBox txtRowLabel = null!;
    private Label lblColumnLabel = null!;
    private TextBox txtColumnLabel = null!;
    private Button btnExtract = null!;
    private Button btnExtractFields = null!;
    private Button btnCopyValue = null!;
    private Button btnCopyJson = null!;
    private Button btnCopyFieldJson = null!;
    private GroupBox grpResult = null!;
    private TableLayoutPanel resultLayout = null!;
    private Label lblStatus = null!;
    private Label lblStatusValue = null!;
    private Label lblValue = null!;
    private Label lblValueValue = null!;
    private Label lblMessage = null!;
    private Label lblMessageValue = null!;
    private GroupBox grpHeaderLine = null!;
    private TextBox txtHeaderLine = null!;
    private GroupBox grpRowLine = null!;
    private TextBox txtRowLine = null!;
    private GroupBox grpJson = null!;
    private TextBox txtJson = null!;
    private GroupBox grpFieldSummary = null!;
    private TextBox txtFieldSummary = null!;
    private GroupBox grpFieldJson = null!;
    private TextBox txtFieldJson = null!;
    private GroupBox grpPageText = null!;
    private TextBox txtFirstPageText = null!;
    private GroupBox grpLog = null!;
    private TextBox txtLog = null!;

    private void InitializeComponent()
    {
        rootLayout = new TableLayoutPanel();
        grpOptions = new GroupBox();
        optionsLayout = new TableLayoutPanel();
        lblPdfPath = new Label();
        txtPdfPath = new TextBox();
        btnBrowsePdf = new Button();
        lblRowLabel = new Label();
        txtRowLabel = new TextBox();
        lblColumnLabel = new Label();
        txtColumnLabel = new TextBox();
        btnExtract = new Button();
        btnExtractFields = new Button();
        btnCopyValue = new Button();
        btnCopyJson = new Button();
        btnCopyFieldJson = new Button();
        grpResult = new GroupBox();
        resultLayout = new TableLayoutPanel();
        lblStatus = new Label();
        lblStatusValue = new Label();
        lblValue = new Label();
        lblValueValue = new Label();
        lblMessage = new Label();
        lblMessageValue = new Label();
        grpHeaderLine = new GroupBox();
        txtHeaderLine = new TextBox();
        grpRowLine = new GroupBox();
        txtRowLine = new TextBox();
        grpJson = new GroupBox();
        txtJson = new TextBox();
        grpFieldSummary = new GroupBox();
        txtFieldSummary = new TextBox();
        grpFieldJson = new GroupBox();
        txtFieldJson = new TextBox();
        grpPageText = new GroupBox();
        txtFirstPageText = new TextBox();
        grpLog = new GroupBox();
        txtLog = new TextBox();
        rootLayout.SuspendLayout();
        grpOptions.SuspendLayout();
        optionsLayout.SuspendLayout();
        grpResult.SuspendLayout();
        resultLayout.SuspendLayout();
        grpHeaderLine.SuspendLayout();
        grpRowLine.SuspendLayout();
        grpJson.SuspendLayout();
        grpFieldSummary.SuspendLayout();
        grpFieldJson.SuspendLayout();
        grpPageText.SuspendLayout();
        grpLog.SuspendLayout();
        SuspendLayout();
        rootLayout.ColumnCount = 2;
        rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 440F));
        rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        rootLayout.Controls.Add(grpOptions, 0, 0);
        rootLayout.Controls.Add(grpJson, 1, 0);
        rootLayout.Controls.Add(grpResult, 0, 1);
        rootLayout.Controls.Add(grpFieldSummary, 0, 2);
        rootLayout.Controls.Add(grpHeaderLine, 0, 3);
        rootLayout.Controls.Add(grpRowLine, 0, 4);
        rootLayout.Controls.Add(grpLog, 0, 5);
        rootLayout.Controls.Add(grpFieldJson, 1, 1);
        rootLayout.Controls.Add(grpPageText, 1, 2);
        rootLayout.Dock = DockStyle.Fill;
        rootLayout.Location = new Point(0, 0);
        rootLayout.Name = "rootLayout";
        rootLayout.Padding = new Padding(12);
        rootLayout.RowCount = 6;
        rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 210F));
        rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 130F));
        rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 150F));
        rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 100F));
        rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 100F));
        rootLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        rootLayout.Size = new Size(1440, 960);

        grpOptions.Controls.Add(optionsLayout);
        grpOptions.Dock = DockStyle.Fill;
        grpOptions.Location = new Point(15, 15);
        grpOptions.Name = "grpOptions";
        grpOptions.Padding = new Padding(10);
        grpOptions.Size = new Size(434, 204);
        grpOptions.TabStop = false;
        grpOptions.Text = "提取参数";

        optionsLayout.ColumnCount = 3;
        optionsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 72F));
        optionsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        optionsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 112F));
        optionsLayout.Controls.Add(lblPdfPath, 0, 0);
        optionsLayout.Controls.Add(txtPdfPath, 1, 0);
        optionsLayout.Controls.Add(btnBrowsePdf, 2, 0);
        optionsLayout.Controls.Add(lblRowLabel, 0, 1);
        optionsLayout.Controls.Add(txtRowLabel, 1, 1);
        optionsLayout.Controls.Add(lblColumnLabel, 0, 2);
        optionsLayout.Controls.Add(txtColumnLabel, 1, 2);
        optionsLayout.Controls.Add(btnExtract, 1, 3);
        optionsLayout.Controls.Add(btnExtractFields, 1, 4);
        optionsLayout.Controls.Add(btnCopyValue, 1, 5);
        optionsLayout.Controls.Add(btnCopyJson, 2, 5);
        optionsLayout.Controls.Add(btnCopyFieldJson, 2, 4);
        optionsLayout.Dock = DockStyle.Fill;
        optionsLayout.Location = new Point(10, 26);
        optionsLayout.Name = "optionsLayout";
        optionsLayout.RowCount = 6;
        optionsLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        optionsLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        optionsLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        optionsLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 38F));
        optionsLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 38F));
        optionsLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 38F));
        optionsLayout.Size = new Size(414, 168);

        lblPdfPath.Dock = DockStyle.Fill;
        lblPdfPath.Text = "PDF";
        lblPdfPath.TextAlign = ContentAlignment.MiddleLeft;
        txtPdfPath.Dock = DockStyle.Fill;
        btnBrowsePdf.Dock = DockStyle.Fill;
        btnBrowsePdf.Text = "选择文件";
        btnBrowsePdf.UseVisualStyleBackColor = true;
        btnBrowsePdf.Click += btnBrowsePdf_Click;

        lblRowLabel.Dock = DockStyle.Fill;
        lblRowLabel.Text = "行名";
        lblRowLabel.TextAlign = ContentAlignment.MiddleLeft;
        txtRowLabel.Dock = DockStyle.Fill;
        optionsLayout.SetColumnSpan(txtRowLabel, 2);

        lblColumnLabel.Dock = DockStyle.Fill;
        lblColumnLabel.Text = "列名";
        lblColumnLabel.TextAlign = ContentAlignment.MiddleLeft;
        txtColumnLabel.Dock = DockStyle.Fill;
        optionsLayout.SetColumnSpan(txtColumnLabel, 2);

        btnExtract.Dock = DockStyle.Fill;
        btnExtract.Text = "提取表格值";
        btnExtract.UseVisualStyleBackColor = true;
        btnExtract.Click += btnExtract_Click;
        optionsLayout.SetColumnSpan(btnExtract, 2);

        btnExtractFields.Dock = DockStyle.Fill;
        btnExtractFields.Text = "提取基础字段";
        btnExtractFields.UseVisualStyleBackColor = true;
        btnExtractFields.Click += btnExtractFields_Click;

        btnCopyFieldJson.Dock = DockStyle.Fill;
        btnCopyFieldJson.Text = "复制字段 JSON";
        btnCopyFieldJson.UseVisualStyleBackColor = true;
        btnCopyFieldJson.Click += btnCopyFieldJson_Click;

        btnCopyValue.Dock = DockStyle.Fill;
        btnCopyValue.Text = "复制提取值";
        btnCopyValue.UseVisualStyleBackColor = true;
        btnCopyValue.Click += btnCopyValue_Click;

        btnCopyJson.Dock = DockStyle.Fill;
        btnCopyJson.Text = "复制表格 JSON";
        btnCopyJson.UseVisualStyleBackColor = true;
        btnCopyJson.Click += btnCopyJson_Click;

        grpResult.Controls.Add(resultLayout);
        grpResult.Dock = DockStyle.Fill;
        grpResult.Location = new Point(15, 225);
        grpResult.Name = "grpResult";
        grpResult.Padding = new Padding(10);
        grpResult.Size = new Size(434, 124);
        grpResult.TabStop = false;
        grpResult.Text = "表格提取结果";

        resultLayout.ColumnCount = 2;
        resultLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 72F));
        resultLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        resultLayout.Controls.Add(lblStatus, 0, 0);
        resultLayout.Controls.Add(lblStatusValue, 1, 0);
        resultLayout.Controls.Add(lblValue, 0, 1);
        resultLayout.Controls.Add(lblValueValue, 1, 1);
        resultLayout.Controls.Add(lblMessage, 0, 2);
        resultLayout.Controls.Add(lblMessageValue, 1, 2);
        resultLayout.Dock = DockStyle.Fill;
        resultLayout.Location = new Point(10, 26);
        resultLayout.RowCount = 3;
        resultLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        resultLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        resultLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        resultLayout.Size = new Size(414, 88);
        lblStatus.Dock = DockStyle.Fill;
        lblStatus.Text = "状态";
        lblStatus.TextAlign = ContentAlignment.MiddleLeft;
        lblStatusValue.Dock = DockStyle.Fill;
        lblStatusValue.Text = "-";
        lblStatusValue.TextAlign = ContentAlignment.MiddleLeft;
        lblValue.Dock = DockStyle.Fill;
        lblValue.Text = "值";
        lblValue.TextAlign = ContentAlignment.MiddleLeft;
        lblValueValue.Dock = DockStyle.Fill;
        lblValueValue.Text = "-";
        lblValueValue.TextAlign = ContentAlignment.MiddleLeft;
        lblMessage.Dock = DockStyle.Fill;
        lblMessage.Text = "消息";
        lblMessage.TextAlign = ContentAlignment.TopLeft;
        lblMessageValue.Dock = DockStyle.Fill;
        lblMessageValue.Text = "-";

        grpFieldSummary.Controls.Add(txtFieldSummary);
        grpFieldSummary.Dock = DockStyle.Fill;
        grpFieldSummary.Location = new Point(15, 355);
        grpFieldSummary.Name = "grpFieldSummary";
        grpFieldSummary.Padding = new Padding(10);
        grpFieldSummary.Size = new Size(434, 144);
        grpFieldSummary.TabStop = false;
        grpFieldSummary.Text = "基础字段摘要";
        txtFieldSummary.Dock = DockStyle.Fill;
        txtFieldSummary.Multiline = true;
        txtFieldSummary.ReadOnly = true;
        txtFieldSummary.ScrollBars = ScrollBars.Vertical;

        grpHeaderLine.Controls.Add(txtHeaderLine);
        grpHeaderLine.Dock = DockStyle.Fill;
        grpHeaderLine.Location = new Point(15, 505);
        grpHeaderLine.Name = "grpHeaderLine";
        grpHeaderLine.Padding = new Padding(10);
        grpHeaderLine.Size = new Size(434, 94);
        grpHeaderLine.TabStop = false;
        grpHeaderLine.Text = "命中表头行";
        txtHeaderLine.Dock = DockStyle.Fill;
        txtHeaderLine.Multiline = true;
        txtHeaderLine.ReadOnly = true;
        txtHeaderLine.ScrollBars = ScrollBars.Vertical;

        grpRowLine.Controls.Add(txtRowLine);
        grpRowLine.Dock = DockStyle.Fill;
        grpRowLine.Location = new Point(15, 605);
        grpRowLine.Name = "grpRowLine";
        grpRowLine.Padding = new Padding(10);
        grpRowLine.Size = new Size(434, 94);
        grpRowLine.TabStop = false;
        grpRowLine.Text = "命中目标行";
        txtRowLine.Dock = DockStyle.Fill;
        txtRowLine.Multiline = true;
        txtRowLine.ReadOnly = true;
        txtRowLine.ScrollBars = ScrollBars.Vertical;

        grpLog.Controls.Add(txtLog);
        grpLog.Dock = DockStyle.Fill;
        grpLog.Location = new Point(15, 705);
        grpLog.Name = "grpLog";
        grpLog.Padding = new Padding(10);
        grpLog.Size = new Size(434, 240);
        grpLog.TabStop = false;
        grpLog.Text = "执行日志";
        txtLog.Dock = DockStyle.Fill;
        txtLog.Multiline = true;
        txtLog.ReadOnly = true;
        txtLog.ScrollBars = ScrollBars.Vertical;

        grpJson.Controls.Add(txtJson);
        grpJson.Dock = DockStyle.Fill;
        grpJson.Location = new Point(455, 15);
        grpJson.Name = "grpJson";
        grpJson.Padding = new Padding(10);
        grpJson.Size = new Size(970, 204);
        grpJson.TabStop = false;
        grpJson.Text = "表格结果 JSON";
        txtJson.Dock = DockStyle.Fill;
        txtJson.Font = new Font("Consolas", 9F);
        txtJson.Multiline = true;
        txtJson.ReadOnly = true;
        txtJson.ScrollBars = ScrollBars.Both;

        grpFieldJson.Controls.Add(txtFieldJson);
        grpFieldJson.Dock = DockStyle.Fill;
        grpFieldJson.Location = new Point(455, 225);
        grpFieldJson.Name = "grpFieldJson";
        grpFieldJson.Padding = new Padding(10);
        grpFieldJson.Size = new Size(970, 124);
        grpFieldJson.TabStop = false;
        grpFieldJson.Text = "基础字段 JSON";
        txtFieldJson.Dock = DockStyle.Fill;
        txtFieldJson.Font = new Font("Consolas", 9F);
        txtFieldJson.Multiline = true;
        txtFieldJson.ReadOnly = true;
        txtFieldJson.ScrollBars = ScrollBars.Both;

        grpPageText.Controls.Add(txtFirstPageText);
        grpPageText.Dock = DockStyle.Fill;
        grpPageText.Location = new Point(455, 355);
        grpPageText.Name = "grpPageText";
        grpPageText.Padding = new Padding(10);
        rootLayout.SetRowSpan(grpPageText, 4);
        grpPageText.Size = new Size(970, 590);
        grpPageText.TabStop = false;
        grpPageText.Text = "首页原始文本";
        txtFirstPageText.Dock = DockStyle.Fill;
        txtFirstPageText.Font = new Font("Consolas", 9F);
        txtFirstPageText.Multiline = true;
        txtFirstPageText.ReadOnly = true;
        txtFirstPageText.ScrollBars = ScrollBars.Both;

        AutoScaleDimensions = new SizeF(7F, 17F);
        AutoScaleMode = AutoScaleMode.Font;
        ClientSize = new Size(1440, 960);
        Controls.Add(rootLayout);
        MinimumSize = new Size(1280, 860);
        Name = "PdfTableValueTestForm";
        StartPosition = FormStartPosition.CenterParent;
        Text = "PDF 提取测试";
        rootLayout.ResumeLayout(false);
        grpOptions.ResumeLayout(false);
        optionsLayout.ResumeLayout(false);
        optionsLayout.PerformLayout();
        grpResult.ResumeLayout(false);
        resultLayout.ResumeLayout(false);
        grpHeaderLine.ResumeLayout(false);
        grpHeaderLine.PerformLayout();
        grpRowLine.ResumeLayout(false);
        grpRowLine.PerformLayout();
        grpJson.ResumeLayout(false);
        grpJson.PerformLayout();
        grpFieldSummary.ResumeLayout(false);
        grpFieldSummary.PerformLayout();
        grpFieldJson.ResumeLayout(false);
        grpFieldJson.PerformLayout();
        grpPageText.ResumeLayout(false);
        grpPageText.PerformLayout();
        grpLog.ResumeLayout(false);
        grpLog.PerformLayout();
        ResumeLayout(false);
    }
}
