using System.Drawing;
using System.Windows.Forms;

namespace Anjian;

public sealed partial class TextOcrTestForm
{
    private TableLayoutPanel rootLayout = null!;
    private TableLayoutPanel leftPanel = null!;
    private TableLayoutPanel previewPanel = null!;
    private TableLayoutPanel rightPanel = null!;
    private GroupBox grpRegion = null!;
    private GroupBox grpOptions = null!;
    private GroupBox grpResult = null!;
    private GroupBox grpRaw = null!;
    private GroupBox grpNormalized = null!;
    private GroupBox grpTableJson = null!;
    private TableLayoutPanel regionLayout = null!;
    private TableLayoutPanel optionsLayout = null!;
    private TableLayoutPanel actionLayout = null!;
    private TableLayoutPanel resultLayout = null!;
    private TableLayoutPanel snippetActions = null!;
    private TableLayoutPanel tableJsonLayout = null!;
    private Label lblRegionX = null!;
    private Label lblRegionY = null!;
    private Label lblRegionWidth = null!;
    private Label lblRegionHeight = null!;
    private Label lblThreshold = null!;
    private Label lblHint = null!;
    private Label lblSourceTitle = null!;
    private Label lblProcessedTitle = null!;
    private Label lblSnippetSection = null!;
    private Label lblLogSection = null!;
    private Label lblResultStatus = null!;
    private Label lblResultElapsed = null!;
    private Label lblResultMessage = null!;
    private TextBox txtRegionX = null!;
    private TextBox txtRegionY = null!;
    private TextBox txtRegionWidth = null!;
    private TextBox txtRegionHeight = null!;
    private TextBox txtThreshold = null!;
    private TextBox txtRaw = null!;
    private TextBox txtNormalized = null!;
    private TextBox txtSnippet = null!;
    private TextBox txtLog = null!;
    private TextBox txtTableJson = null!;
    private CheckBox chkGrayscale = null!;
    private CheckBox chkBinarization = null!;
    private CheckBox chkScale2x = null!;
    private PictureBox picSource = null!;
    private PictureBox picProcessed = null!;
    private Label lblStatusValue = null!;
    private Label lblElapsedValue = null!;
    private Label lblMessageValue = null!;
    private Button btnCaptureRegion = null!;
    private Button btnPickRegion = null!;
    private Button btnExecuteOcr = null!;
    private Button btnExecuteTableJson = null!;
    private Button btnGenerateSnippet = null!;
    private Button btnCopySnippet = null!;
    private Button btnCopyText = null!;
    private Button btnCopyTableJson = null!;

    private void InitializeComponent()
    {
        rootLayout = new TableLayoutPanel();
        leftPanel = new TableLayoutPanel();
        grpRegion = new GroupBox();
        regionLayout = new TableLayoutPanel();
        lblRegionX = new Label();
        txtRegionX = new TextBox();
        lblRegionY = new Label();
        txtRegionY = new TextBox();
        lblRegionWidth = new Label();
        txtRegionWidth = new TextBox();
        lblRegionHeight = new Label();
        txtRegionHeight = new TextBox();
        btnPickRegion = new Button();
        grpOptions = new GroupBox();
        optionsLayout = new TableLayoutPanel();
        chkGrayscale = new CheckBox();
        chkBinarization = new CheckBox();
        chkScale2x = new CheckBox();
        lblThreshold = new Label();
        txtThreshold = new TextBox();
        actionLayout = new TableLayoutPanel();
        btnCaptureRegion = new Button();
        btnExecuteOcr = new Button();
        btnExecuteTableJson = new Button();
        btnGenerateSnippet = new Button();
        btnCopyText = new Button();
        lblHint = new Label();
        previewPanel = new TableLayoutPanel();
        lblSourceTitle = new Label();
        picSource = new PictureBox();
        lblProcessedTitle = new Label();
        picProcessed = new PictureBox();
        rightPanel = new TableLayoutPanel();
        grpResult = new GroupBox();
        resultLayout = new TableLayoutPanel();
        lblResultStatus = new Label();
        lblStatusValue = new Label();
        lblResultElapsed = new Label();
        lblElapsedValue = new Label();
        lblResultMessage = new Label();
        lblMessageValue = new Label();
        lblSnippetSection = new Label();
        snippetActions = new TableLayoutPanel();
        btnCopySnippet = new Button();
        txtSnippet = new TextBox();
        grpRaw = new GroupBox();
        txtRaw = new TextBox();
        grpNormalized = new GroupBox();
        txtNormalized = new TextBox();
        grpTableJson = new GroupBox();
        tableJsonLayout = new TableLayoutPanel();
        btnCopyTableJson = new Button();
        txtTableJson = new TextBox();
        lblLogSection = new Label();
        txtLog = new TextBox();
        rootLayout.SuspendLayout();
        leftPanel.SuspendLayout();
        grpRegion.SuspendLayout();
        regionLayout.SuspendLayout();
        grpOptions.SuspendLayout();
        optionsLayout.SuspendLayout();
        actionLayout.SuspendLayout();
        previewPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)picSource).BeginInit();
        ((System.ComponentModel.ISupportInitialize)picProcessed).BeginInit();
        rightPanel.SuspendLayout();
        grpResult.SuspendLayout();
        resultLayout.SuspendLayout();
        snippetActions.SuspendLayout();
        grpRaw.SuspendLayout();
        grpNormalized.SuspendLayout();
        grpTableJson.SuspendLayout();
        tableJsonLayout.SuspendLayout();
        SuspendLayout();
        rootLayout.ColumnCount = 3;
        rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 330F));
        rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 390F));
        rootLayout.Controls.Add(leftPanel, 0, 0);
        rootLayout.Controls.Add(previewPanel, 1, 0);
        rootLayout.Controls.Add(rightPanel, 2, 0);
        rootLayout.Dock = DockStyle.Fill;
        rootLayout.Location = new Point(0, 0);
        rootLayout.Name = "rootLayout";
        rootLayout.Padding = new Padding(12);
        rootLayout.RowCount = 1;
        rootLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        rootLayout.Size = new Size(1600, 920);
        rootLayout.TabIndex = 0;
        leftPanel.ColumnCount = 1;
        leftPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        leftPanel.Controls.Add(grpRegion, 0, 0);
        leftPanel.Controls.Add(grpOptions, 0, 1);
        leftPanel.Controls.Add(actionLayout, 0, 2);
        leftPanel.Controls.Add(lblHint, 0, 3);
        leftPanel.Dock = DockStyle.Fill;
        leftPanel.Location = new Point(15, 15);
        leftPanel.Name = "leftPanel";
        leftPanel.RowCount = 4;
        leftPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 220F));
        leftPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 200F));
        leftPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 210F));
        leftPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        leftPanel.Size = new Size(324, 890);
        leftPanel.TabIndex = 0;
        grpRegion.Controls.Add(regionLayout);
        grpRegion.Dock = DockStyle.Fill;
        grpRegion.Location = new Point(3, 3);
        grpRegion.Name = "grpRegion";
        grpRegion.Padding = new Padding(10);
        grpRegion.Size = new Size(318, 214);
        grpRegion.TabIndex = 0;
        grpRegion.TabStop = false;
        grpRegion.Text = "识别区域";
        regionLayout.ColumnCount = 2;
        regionLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 96F));
        regionLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        regionLayout.Controls.Add(lblRegionX, 0, 0);
        regionLayout.Controls.Add(txtRegionX, 1, 0);
        regionLayout.Controls.Add(lblRegionY, 0, 1);
        regionLayout.Controls.Add(txtRegionY, 1, 1);
        regionLayout.Controls.Add(lblRegionWidth, 0, 2);
        regionLayout.Controls.Add(txtRegionWidth, 1, 2);
        regionLayout.Controls.Add(lblRegionHeight, 0, 3);
        regionLayout.Controls.Add(txtRegionHeight, 1, 3);
        regionLayout.Controls.Add(btnPickRegion, 0, 4);
        regionLayout.Dock = DockStyle.Fill;
        regionLayout.Location = new Point(10, 26);
        regionLayout.Name = "regionLayout";
        regionLayout.RowCount = 5;
        regionLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        regionLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        regionLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        regionLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        regionLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
        regionLayout.Size = new Size(298, 178);
        regionLayout.TabIndex = 0;
        lblRegionX.Dock = DockStyle.Fill;
        lblRegionX.Location = new Point(3, 0);
        lblRegionX.Name = "lblRegionX";
        lblRegionX.Size = new Size(90, 34);
        lblRegionX.Text = "X";
        lblRegionX.TextAlign = ContentAlignment.MiddleLeft;
        txtRegionX.Dock = DockStyle.Fill;
        txtRegionX.Location = new Point(99, 3);
        txtRegionX.Name = "txtRegionX";
        txtRegionX.Size = new Size(196, 23);
        lblRegionY.Dock = DockStyle.Fill;
        lblRegionY.Location = new Point(3, 34);
        lblRegionY.Name = "lblRegionY";
        lblRegionY.Size = new Size(90, 34);
        lblRegionY.Text = "Y";
        lblRegionY.TextAlign = ContentAlignment.MiddleLeft;
        txtRegionY.Dock = DockStyle.Fill;
        txtRegionY.Location = new Point(99, 37);
        txtRegionY.Name = "txtRegionY";
        txtRegionY.Size = new Size(196, 23);
        lblRegionWidth.Dock = DockStyle.Fill;
        lblRegionWidth.Location = new Point(3, 68);
        lblRegionWidth.Name = "lblRegionWidth";
        lblRegionWidth.Size = new Size(90, 34);
        lblRegionWidth.Text = "Width";
        lblRegionWidth.TextAlign = ContentAlignment.MiddleLeft;
        txtRegionWidth.Dock = DockStyle.Fill;
        txtRegionWidth.Location = new Point(99, 71);
        txtRegionWidth.Name = "txtRegionWidth";
        txtRegionWidth.Size = new Size(196, 23);
        lblRegionHeight.Dock = DockStyle.Fill;
        lblRegionHeight.Location = new Point(3, 102);
        lblRegionHeight.Name = "lblRegionHeight";
        lblRegionHeight.Size = new Size(90, 34);
        lblRegionHeight.Text = "Height";
        lblRegionHeight.TextAlign = ContentAlignment.MiddleLeft;
        txtRegionHeight.Dock = DockStyle.Fill;
        txtRegionHeight.Location = new Point(99, 105);
        txtRegionHeight.Name = "txtRegionHeight";
        txtRegionHeight.Size = new Size(196, 23);
        btnPickRegion.Dock = DockStyle.Fill;
        btnPickRegion.Location = new Point(3, 139);
        btnPickRegion.Name = "btnPickRegion";
        btnPickRegion.Size = new Size(292, 36);
        btnPickRegion.TabIndex = 8;
        btnPickRegion.Text = "选取区域";
        btnPickRegion.UseVisualStyleBackColor = true;
        btnPickRegion.Click += btnPickRegion_Click;
        regionLayout.SetColumnSpan(btnPickRegion, 2);
        grpOptions.Controls.Add(optionsLayout);
        grpOptions.Dock = DockStyle.Fill;
        grpOptions.Location = new Point(3, 223);
        grpOptions.Name = "grpOptions";
        grpOptions.Padding = new Padding(10);
        grpOptions.Size = new Size(318, 194);
        grpOptions.TabIndex = 1;
        grpOptions.TabStop = false;
        grpOptions.Text = "OCR 参数";
        optionsLayout.ColumnCount = 2;
        optionsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 96F));
        optionsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        optionsLayout.Controls.Add(chkGrayscale, 1, 0);
        optionsLayout.Controls.Add(chkBinarization, 1, 1);
        optionsLayout.Controls.Add(chkScale2x, 1, 2);
        optionsLayout.Controls.Add(lblThreshold, 0, 3);
        optionsLayout.Controls.Add(txtThreshold, 1, 3);
        optionsLayout.Dock = DockStyle.Fill;
        optionsLayout.Location = new Point(10, 26);
        optionsLayout.Name = "optionsLayout";
        optionsLayout.RowCount = 4;
        optionsLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        optionsLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        optionsLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        optionsLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        optionsLayout.Size = new Size(298, 158);
        optionsLayout.TabIndex = 0;
        chkGrayscale.Checked = true;
        chkGrayscale.CheckState = CheckState.Checked;
        chkGrayscale.Dock = DockStyle.Fill;
        chkGrayscale.Location = new Point(99, 3);
        chkGrayscale.Name = "chkGrayscale";
        chkGrayscale.Size = new Size(196, 28);
        chkGrayscale.Text = "启用灰度";
        chkGrayscale.CheckedChanged += chkOptions_CheckedChanged;
        chkBinarization.Dock = DockStyle.Fill;
        chkBinarization.Location = new Point(99, 37);
        chkBinarization.Name = "chkBinarization";
        chkBinarization.Size = new Size(196, 28);
        chkBinarization.Text = "启用二值化";
        chkBinarization.CheckedChanged += chkOptions_CheckedChanged;
        chkScale2x.Dock = DockStyle.Fill;
        chkScale2x.Location = new Point(99, 71);
        chkScale2x.Name = "chkScale2x";
        chkScale2x.Size = new Size(196, 28);
        chkScale2x.Text = "启用放大 2x";
        chkScale2x.CheckedChanged += chkOptions_CheckedChanged;
        lblThreshold.Dock = DockStyle.Fill;
        lblThreshold.Location = new Point(3, 102);
        lblThreshold.Name = "lblThreshold";
        lblThreshold.Size = new Size(90, 56);
        lblThreshold.Text = "二值化阈值";
        lblThreshold.TextAlign = ContentAlignment.MiddleLeft;
        txtThreshold.Dock = DockStyle.Fill;
        txtThreshold.Location = new Point(99, 105);
        txtThreshold.Name = "txtThreshold";
        txtThreshold.Size = new Size(196, 23);
        txtThreshold.Text = "160";
        txtThreshold.TextChanged += txtThreshold_TextChanged;
        actionLayout.ColumnCount = 1;
        actionLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        actionLayout.Controls.Add(btnCaptureRegion, 0, 0);
        actionLayout.Controls.Add(btnExecuteOcr, 0, 1);
        actionLayout.Controls.Add(btnExecuteTableJson, 0, 2);
        actionLayout.Controls.Add(btnGenerateSnippet, 0, 3);
        actionLayout.Controls.Add(btnCopyText, 0, 4);
        actionLayout.Dock = DockStyle.Fill;
        actionLayout.Location = new Point(3, 423);
        actionLayout.Name = "actionLayout";
        actionLayout.RowCount = 5;
        actionLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
        actionLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
        actionLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
        actionLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
        actionLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
        actionLayout.Size = new Size(318, 204);
        actionLayout.TabIndex = 2;
        btnCaptureRegion.Dock = DockStyle.Fill;
        btnCaptureRegion.Location = new Point(3, 3);
        btnCaptureRegion.Name = "btnCaptureRegion";
        btnCaptureRegion.Size = new Size(312, 34);
        btnCaptureRegion.Text = "截图当前区域";
        btnCaptureRegion.UseVisualStyleBackColor = true;
        btnCaptureRegion.Click += btnCaptureRegion_Click;
        btnExecuteOcr.Dock = DockStyle.Fill;
        btnExecuteOcr.Location = new Point(3, 43);
        btnExecuteOcr.Name = "btnExecuteOcr";
        btnExecuteOcr.Size = new Size(312, 34);
        btnExecuteOcr.Text = "识别当前区域";
        btnExecuteOcr.UseVisualStyleBackColor = true;
        btnExecuteOcr.Click += btnExecuteOcr_Click;
        btnExecuteTableJson.Dock = DockStyle.Fill;
        btnExecuteTableJson.Location = new Point(3, 83);
        btnExecuteTableJson.Name = "btnExecuteTableJson";
        btnExecuteTableJson.Size = new Size(312, 34);
        btnExecuteTableJson.Text = "识别当前区域为 JSON";
        btnExecuteTableJson.UseVisualStyleBackColor = true;
        btnExecuteTableJson.Click += btnExecuteTableJson_Click;
        btnGenerateSnippet.Dock = DockStyle.Fill;
        btnGenerateSnippet.Location = new Point(3, 123);
        btnGenerateSnippet.Name = "btnGenerateSnippet";
        btnGenerateSnippet.Size = new Size(312, 34);
        btnGenerateSnippet.Text = "生成代码片段";
        btnGenerateSnippet.UseVisualStyleBackColor = true;
        btnGenerateSnippet.Click += btnGenerateSnippet_Click;
        btnCopyText.Dock = DockStyle.Fill;
        btnCopyText.Location = new Point(3, 163);
        btnCopyText.Name = "btnCopyText";
        btnCopyText.Size = new Size(312, 38);
        btnCopyText.Text = "复制识别文本";
        btnCopyText.UseVisualStyleBackColor = true;
        btnCopyText.Click += btnCopyText_Click;
        lblHint.Dock = DockStyle.Fill;
        lblHint.ForeColor = Color.DimGray;
        lblHint.Location = new Point(3, 630);
        lblHint.Name = "lblHint";
        lblHint.Size = new Size(318, 260);
        lblHint.Text = "建议先截图预览，再逐项调节 OCR 参数。普通文字识别会在原图上叠加文字框；表格识别会把当前区域输出为 JSON，方便直接复制到自动化工程里验证。";
        previewPanel.ColumnCount = 1;
        previewPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        previewPanel.Controls.Add(lblSourceTitle, 0, 0);
        previewPanel.Controls.Add(picSource, 0, 1);
        previewPanel.Controls.Add(lblProcessedTitle, 0, 2);
        previewPanel.Controls.Add(picProcessed, 0, 3);
        previewPanel.Dock = DockStyle.Fill;
        previewPanel.Location = new Point(345, 15);
        previewPanel.Name = "previewPanel";
        previewPanel.RowCount = 4;
        previewPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        previewPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
        previewPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        previewPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
        previewPanel.Size = new Size(850, 890);
        previewPanel.TabIndex = 1;
        lblSourceTitle.Dock = DockStyle.Fill;
        lblSourceTitle.Font = new Font("Microsoft YaHei UI", 10F, FontStyle.Bold);
        lblSourceTitle.Location = new Point(3, 0);
        lblSourceTitle.Name = "lblSourceTitle";
        lblSourceTitle.Size = new Size(844, 28);
        lblSourceTitle.Text = "原始截图";
        lblSourceTitle.TextAlign = ContentAlignment.MiddleLeft;
        picSource.BackColor = Color.WhiteSmoke;
        picSource.BorderStyle = BorderStyle.FixedSingle;
        picSource.Dock = DockStyle.Fill;
        picSource.Location = new Point(3, 31);
        picSource.Name = "picSource";
        picSource.Size = new Size(844, 425);
        picSource.SizeMode = PictureBoxSizeMode.Zoom;
        lblProcessedTitle.Dock = DockStyle.Fill;
        lblProcessedTitle.Font = new Font("Microsoft YaHei UI", 10F, FontStyle.Bold);
        lblProcessedTitle.Location = new Point(3, 459);
        lblProcessedTitle.Name = "lblProcessedTitle";
        lblProcessedTitle.Size = new Size(844, 28);
        lblProcessedTitle.Text = "预处理预览";
        lblProcessedTitle.TextAlign = ContentAlignment.MiddleLeft;
        picProcessed.BackColor = Color.WhiteSmoke;
        picProcessed.BorderStyle = BorderStyle.FixedSingle;
        picProcessed.Dock = DockStyle.Fill;
        picProcessed.Location = new Point(3, 490);
        picProcessed.Name = "picProcessed";
        picProcessed.Size = new Size(844, 397);
        picProcessed.SizeMode = PictureBoxSizeMode.Zoom;
        rightPanel.ColumnCount = 1;
        rightPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        rightPanel.Controls.Add(grpResult, 0, 0);
        rightPanel.Controls.Add(lblSnippetSection, 0, 1);
        rightPanel.Controls.Add(snippetActions, 0, 2);
        rightPanel.Controls.Add(txtSnippet, 0, 3);
        rightPanel.Controls.Add(grpRaw, 0, 4);
        rightPanel.Controls.Add(grpNormalized, 0, 5);
        rightPanel.Controls.Add(grpTableJson, 0, 6);
        rightPanel.Controls.Add(lblLogSection, 0, 7);
        rightPanel.Controls.Add(txtLog, 0, 8);
        rightPanel.Dock = DockStyle.Fill;
        rightPanel.Location = new Point(1201, 15);
        rightPanel.Name = "rightPanel";
        rightPanel.RowCount = 9;
        rightPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 130F));
        rightPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        rightPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 38F));
        rightPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 150F));
        rightPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 120F));
        rightPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 120F));
        rightPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 180F));
        rightPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        rightPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        rightPanel.Size = new Size(384, 890);
        rightPanel.TabIndex = 2;
        grpResult.Controls.Add(resultLayout);
        grpResult.Dock = DockStyle.Fill;
        grpResult.Location = new Point(3, 3);
        grpResult.Name = "grpResult";
        grpResult.Padding = new Padding(10);
        grpResult.Size = new Size(378, 124);
        grpResult.TabIndex = 0;
        grpResult.TabStop = false;
        grpResult.Text = "识别结果";
        resultLayout.ColumnCount = 2;
        resultLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 72F));
        resultLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        resultLayout.Controls.Add(lblResultStatus, 0, 0);
        resultLayout.Controls.Add(lblStatusValue, 1, 0);
        resultLayout.Controls.Add(lblResultElapsed, 0, 1);
        resultLayout.Controls.Add(lblElapsedValue, 1, 1);
        resultLayout.Controls.Add(lblResultMessage, 0, 2);
        resultLayout.Controls.Add(lblMessageValue, 1, 2);
        resultLayout.Dock = DockStyle.Fill;
        resultLayout.Location = new Point(10, 26);
        resultLayout.Name = "resultLayout";
        resultLayout.RowCount = 3;
        resultLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        resultLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        resultLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        resultLayout.Size = new Size(358, 88);
        lblResultStatus.Dock = DockStyle.Fill;
        lblResultStatus.Location = new Point(3, 0);
        lblResultStatus.Name = "lblResultStatus";
        lblResultStatus.Size = new Size(66, 28);
        lblResultStatus.Text = "状态";
        lblResultStatus.TextAlign = ContentAlignment.MiddleLeft;
        lblStatusValue.Dock = DockStyle.Fill;
        lblStatusValue.Location = new Point(75, 0);
        lblStatusValue.Name = "lblStatusValue";
        lblStatusValue.Size = new Size(280, 28);
        lblStatusValue.Text = "-";
        lblStatusValue.TextAlign = ContentAlignment.MiddleLeft;
        lblResultElapsed.Dock = DockStyle.Fill;
        lblResultElapsed.Location = new Point(3, 28);
        lblResultElapsed.Name = "lblResultElapsed";
        lblResultElapsed.Size = new Size(66, 28);
        lblResultElapsed.Text = "耗时(ms)";
        lblResultElapsed.TextAlign = ContentAlignment.MiddleLeft;
        lblElapsedValue.Dock = DockStyle.Fill;
        lblElapsedValue.Location = new Point(75, 28);
        lblElapsedValue.Name = "lblElapsedValue";
        lblElapsedValue.Size = new Size(280, 28);
        lblElapsedValue.Text = "-";
        lblElapsedValue.TextAlign = ContentAlignment.MiddleLeft;
        lblResultMessage.Dock = DockStyle.Fill;
        lblResultMessage.Location = new Point(3, 56);
        lblResultMessage.Name = "lblResultMessage";
        lblResultMessage.Size = new Size(66, 32);
        lblResultMessage.Text = "消息";
        lblResultMessage.TextAlign = ContentAlignment.TopLeft;
        lblMessageValue.Dock = DockStyle.Fill;
        lblMessageValue.Location = new Point(75, 56);
        lblMessageValue.Name = "lblMessageValue";
        lblMessageValue.Size = new Size(280, 32);
        lblMessageValue.Text = "-";
        lblSnippetSection.Dock = DockStyle.Fill;
        lblSnippetSection.Font = new Font("Microsoft YaHei UI", 9F, FontStyle.Bold);
        lblSnippetSection.Location = new Point(3, 130);
        lblSnippetSection.Name = "lblSnippetSection";
        lblSnippetSection.Size = new Size(378, 26);
        lblSnippetSection.Text = "代码片段";
        lblSnippetSection.TextAlign = ContentAlignment.MiddleLeft;
        snippetActions.ColumnCount = 1;
        snippetActions.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        snippetActions.Controls.Add(btnCopySnippet, 0, 0);
        snippetActions.Dock = DockStyle.Fill;
        snippetActions.Location = new Point(3, 159);
        snippetActions.Name = "snippetActions";
        snippetActions.RowCount = 1;
        snippetActions.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        snippetActions.Size = new Size(378, 32);
        btnCopySnippet.Dock = DockStyle.Right;
        btnCopySnippet.Location = new Point(255, 3);
        btnCopySnippet.Name = "btnCopySnippet";
        btnCopySnippet.Size = new Size(120, 26);
        btnCopySnippet.Text = "复制代码片段";
        btnCopySnippet.UseVisualStyleBackColor = true;
        btnCopySnippet.Click += btnCopySnippet_Click;
        txtSnippet.Dock = DockStyle.Fill;
        txtSnippet.Font = new Font("Consolas", 9F);
        txtSnippet.Location = new Point(3, 197);
        txtSnippet.Multiline = true;
        txtSnippet.Name = "txtSnippet";
        txtSnippet.ReadOnly = true;
        txtSnippet.ScrollBars = ScrollBars.Both;
        txtSnippet.Size = new Size(378, 144);
        grpRaw.Controls.Add(txtRaw);
        grpRaw.Dock = DockStyle.Fill;
        grpRaw.Location = new Point(3, 347);
        grpRaw.Name = "grpRaw";
        grpRaw.Padding = new Padding(10);
        grpRaw.Size = new Size(378, 114);
        grpRaw.TabStop = false;
        grpRaw.Text = "原始文本";
        txtRaw.Dock = DockStyle.Fill;
        txtRaw.Font = new Font("Consolas", 9F);
        txtRaw.Multiline = true;
        txtRaw.Name = "txtRaw";
        txtRaw.ReadOnly = true;
        txtRaw.ScrollBars = ScrollBars.Vertical;
        grpNormalized.Controls.Add(txtNormalized);
        grpNormalized.Dock = DockStyle.Fill;
        grpNormalized.Location = new Point(3, 467);
        grpNormalized.Name = "grpNormalized";
        grpNormalized.Padding = new Padding(10);
        grpNormalized.Size = new Size(378, 114);
        grpNormalized.TabStop = false;
        grpNormalized.Text = "归一化文本";
        txtNormalized.Dock = DockStyle.Fill;
        txtNormalized.Font = new Font("Consolas", 9F);
        txtNormalized.Multiline = true;
        txtNormalized.Name = "txtNormalized";
        txtNormalized.ReadOnly = true;
        txtNormalized.ScrollBars = ScrollBars.Vertical;
        grpTableJson.Controls.Add(tableJsonLayout);
        grpTableJson.Dock = DockStyle.Fill;
        grpTableJson.Location = new Point(3, 587);
        grpTableJson.Name = "grpTableJson";
        grpTableJson.Padding = new Padding(10);
        grpTableJson.Size = new Size(378, 174);
        grpTableJson.TabStop = false;
        grpTableJson.Text = "表格 JSON";
        tableJsonLayout.ColumnCount = 1;
        tableJsonLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        tableJsonLayout.Controls.Add(btnCopyTableJson, 0, 0);
        tableJsonLayout.Controls.Add(txtTableJson, 0, 1);
        tableJsonLayout.Dock = DockStyle.Fill;
        tableJsonLayout.Location = new Point(10, 26);
        tableJsonLayout.Name = "tableJsonLayout";
        tableJsonLayout.RowCount = 2;
        tableJsonLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        tableJsonLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        tableJsonLayout.Size = new Size(358, 138);
        btnCopyTableJson.Dock = DockStyle.Right;
        btnCopyTableJson.Location = new Point(238, 3);
        btnCopyTableJson.Name = "btnCopyTableJson";
        btnCopyTableJson.Size = new Size(117, 26);
        btnCopyTableJson.Text = "复制表格 JSON";
        btnCopyTableJson.UseVisualStyleBackColor = true;
        btnCopyTableJson.Click += btnCopyTableJson_Click;
        txtTableJson.Dock = DockStyle.Fill;
        txtTableJson.Font = new Font("Consolas", 9F);
        txtTableJson.Location = new Point(3, 35);
        txtTableJson.Multiline = true;
        txtTableJson.Name = "txtTableJson";
        txtTableJson.ReadOnly = true;
        txtTableJson.ScrollBars = ScrollBars.Both;
        txtTableJson.Size = new Size(352, 100);
        lblLogSection.Dock = DockStyle.Fill;
        lblLogSection.Font = new Font("Microsoft YaHei UI", 9F, FontStyle.Bold);
        lblLogSection.Location = new Point(3, 764);
        lblLogSection.Name = "lblLogSection";
        lblLogSection.Size = new Size(378, 26);
        lblLogSection.Text = "执行日志";
        lblLogSection.TextAlign = ContentAlignment.MiddleLeft;
        txtLog.Dock = DockStyle.Fill;
        txtLog.Font = new Font("Consolas", 9F);
        txtLog.Location = new Point(3, 793);
        txtLog.Multiline = true;
        txtLog.Name = "txtLog";
        txtLog.ReadOnly = true;
        txtLog.ScrollBars = ScrollBars.Vertical;
        txtLog.Size = new Size(378, 94);
        AutoScaleDimensions = new SizeF(7F, 17F);
        AutoScaleMode = AutoScaleMode.Font;
        ClientSize = new Size(1600, 920);
        Controls.Add(rootLayout);
        MinimumSize = new Size(1480, 860);
        Name = "TextOcrTestForm";
        StartPosition = FormStartPosition.CenterParent;
        Text = "文字识别测试";
        rootLayout.ResumeLayout(false);
        leftPanel.ResumeLayout(false);
        grpRegion.ResumeLayout(false);
        regionLayout.ResumeLayout(false);
        regionLayout.PerformLayout();
        grpOptions.ResumeLayout(false);
        optionsLayout.ResumeLayout(false);
        optionsLayout.PerformLayout();
        actionLayout.ResumeLayout(false);
        previewPanel.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)picSource).EndInit();
        ((System.ComponentModel.ISupportInitialize)picProcessed).EndInit();
        rightPanel.ResumeLayout(false);
        rightPanel.PerformLayout();
        grpResult.ResumeLayout(false);
        resultLayout.ResumeLayout(false);
        snippetActions.ResumeLayout(false);
        grpRaw.ResumeLayout(false);
        grpRaw.PerformLayout();
        grpNormalized.ResumeLayout(false);
        grpNormalized.PerformLayout();
        grpTableJson.ResumeLayout(false);
        tableJsonLayout.ResumeLayout(false);
        tableJsonLayout.PerformLayout();
        ResumeLayout(false);
    }
}
