<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Tesseract" Version="5.2.0" />
    <PackageReference Include="Tesseract.Drawing" Version="5.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="MainForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="MainForm.Designer.cs">
      <DependentUpon>MainForm.cs</DependentUpon>
    </Compile>
    <Compile Update="ImageMatchTestForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="ImageMatchTestForm.Designer.cs">
      <DependentUpon>ImageMatchTestForm.cs</DependentUpon>
    </Compile>
    <Compile Update="AmountOcrTestForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="AmountOcrTestForm.Designer.cs">
      <DependentUpon>AmountOcrTestForm.cs</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="tessdata\\eng.traineddata">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
